### ISSUE TITLE
Execute서버와 Evaluation서버 분리 및 cicd/kuber 관련 설정

### ISSUE THREAD

**Issue by 724thomas** [CodeMentor-CodingSite/JavaServer-microservice#17]
##  이슈 내용
> 현재 execute서버에 구현되어 있는 execute, evaluation 도메인 분리

<br>

##  작업 사항
- [x] Evaluation 서버 세팅
- [x] cicd 세팅
- [x] kuber 관련 설정
- [x] .bat파일 생성

<br>

##  관련 이슈
- #이슈 번호

<br>

## 기타사항

<br>

**Comment by hoonii2** [comment]
.bar 이 머지???

**Comment by 724thomas** [comment]
> .bar 이 머지???

.bat이 오타난듯
