### ISSUE TITLE
User 기능 개발

### ISSUE THREAD

**Issue by hoonii2** [CodeMentor-CodingSite/JavaServer-microservice#3]
##  이슈 내용
User 관련 기능 개발

<br>

##  작업 사항
- [x] User DB Entity, Repository 구현
- [x] 회원가입, 로그인 기능 개발
- [x] 로그아웃 기능 개발
- [x] Refresh Token DB 저장
  - [x] 추후 Redis 캐싱 적용 성능 비교 
- [x] API Gateway JWT Filter 기능 개발

<br>

##  관련 이슈

<br>

## 기타사항

<br>

**Comment by EUNSUN23** [comment]
혹시 비밀번호 수정 기능도 개발 하시나요? 비밀번호 수정 페이지도 퍼블리싱에 넣어야 하나 해서요 

리트코드에는 사용자 이메일로 비밀번호 수정 링크 보내서 수정하게끔 하는 것 같습니다.

**Comment by 724thomas** [comment]
> 혹시 비밀번호 수정 기능도 개발 하시나요? 비밀번호 수정 페이지도 퍼블리싱에 넣어야 하나 해서요
> 
> 리트코드에는 사용자 이메일로 비밀번호 수정 링크 보내서 수정하게끔 하는 것 같습니다.

비밀번호 수정도 개발합니다. 후자로 안하고 회원정보 변경에서 Put요청으로 하려고합니다
참고: https://code-mentor.atlassian.net/wiki/spaces/CodeMentor1/pages/5570578

**Comment by EUNSUN23** [comment]
네 알겠습니다. 그리고 아이디/비밀번호는 형식 따로 없을까요? 프론트에서 validation 어떻게 할까요?

**Comment by EUNSUN23** [comment]
네 알겠습니다. 그리고 아이디/비밀번호는 형식 따로 없을까요? 프론트에서 validation 어떻게 해야하는지 궁금해서요

**Comment by 724thomas** [comment]
> 네 알겠습니다. 그리고 아이디/비밀번호는 형식 따로 없을까요? 프론트에서 validation 어떻게 해야하는지 궁금해서요

이메일에서 validation은 중복체크만 계획이 있어요. 나머지 형식 정한건 없습니다. 어떻게 하는게 좋을까요?

**Comment by EUNSUN23** [comment]
아이디는 영문/숫자 6-12 자리, 비밀번호는 영문/숫자/특수문자 8-12자리  이렇게 어떤가요?

**Comment by 724thomas** [comment]
> 아이디는 영문/숫자 6-12 자리, 비밀번호는 영문/숫자/특수문자 8-12자리 이렇게 어떤가요?

아이디가 닉네임을 말씀하시는거죠? 닉네임도 validation이 필요할까요? 비밀번호는 말씀해주신대로 가면 좋을것 같습니다

**Comment by EUNSUN23** [comment]
네 닉네임이요. 보통 사이트들에서 닉네임도 validation 하는것같아서요.

**Comment by 724thomas** [comment]
> 네 닉네임이요. 보통 사이트들에서 닉네임도 validation 하는것같아서요. 

아 그런가요? 어차피 두 기능 비슷해서 상관없을거 같습니다. 그러면 닉네임 중복확인도 필요하겠네요
