### ISSUE TITLE
Evaluation서버에서 Java버전 코드 작성.

### ISSUE THREAD

**Issue by 724thomas** [CodeMentor-CodingSite/JavaServer-microservice#81]
##  이슈 내용
> Python은 현재 문제 없이 명령어를 잘 작성중. (지금까지는 converter가 필요없는 테스트만 진행).
자바코드를 실행할 수 있는 명령어가 필요함.

<br>

##  작업 사항
- [ ] Evaluate 서버의 EvauationService에서 Java버전 명령어 생성.

<br>

##  관련 이슈
- #이슈 번호

<br>

## 기타사항
로컬에서 JSch 연결이 안되는데, 설정값 다시 공유좀...

<br>

**Comment by hoonii2** [comment]
java 버전 명령어가 무슨 말이지 ??
java usercode 를 최종 코드로 만드는 로직이 필요하다는건가??

jsch 로컬에서 API 요청통해서 ssh 연결하고 명령어 실행하고 출력하는 테스트 문제없음 정확한 증상을 말해줘
![image](https://github.com/CodeMentor-CodingSite/JavaServer-microservice/assets/17640541/56b5032d-4d1d-4380-aa55-7caadbce6bc8)
![image](https://github.com/CodeMentor-CodingSite/JavaServer-microservice/assets/17640541/93b622b2-d6e1-4345-9b9f-acb78f01f8a7)
